# Generated by Django 4.2.3 on 2025-12-29 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('minimal', 'Minimal')], max_length=20)),
                ('risk_score', models.FloatField()),
                ('vulnerability_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('ai_insights', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='scanning.scan')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='scanning.scantarget')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('performance_metrics', models.JSONField(default=dict)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('training_samples', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='ai_risk_sco_model_t_483cf5_idx'), models.Index(fields=['-created_at'], name='ai_risk_sco_created_49e661_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('exploitability_score', models.FloatField()),
                ('impact_score', models.FloatField()),
                ('business_impact_score', models.FloatField(blank=True, null=True)),
                ('ai_model_version', models.CharField(default='v1.0', max_length=50)),
                ('confidence', models.FloatField()),
                ('factors', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_analysis', models.JSONField(default=dict)),
                ('risk_trend', models.CharField(blank=True, choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('decreasing', 'Decreasing')], max_length=20)),
                ('predicted_exploit_likelihood', models.FloatField(blank=True, null=True)),
                ('remediation_priority', models.IntegerField(default=0)),
                ('vulnerability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='scanning.vulnerability')),
            ],
            options={
                'ordering': ['-overall_score'],
                'indexes': [models.Index(fields=['vulnerability'], name='ai_risk_sco_vulnera_7d2e57_idx'), models.Index(fields=['-overall_score'], name='ai_risk_sco_overall_b0299b_idx'), models.Index(fields=['remediation_priority', '-overall_score'], name='ai_risk_sco_remedia_1cf72a_idx')],
            },
        ),
    ]
