# Generated by Django 4.2.3 on 2026-05-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_risk_scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['scan', '-generated_at'], name='ai_risk_sco_scan_id_dc0a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['target', '-generated_at'], name='ai_risk_sco_target__0c49e6_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['overall_risk', '-generated_at'], name='ai_risk_sco_overall_01375b_idx'),
        ),
    ]
