# Generated by Django 4.2.3 on 2026-02-10 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('severity_threshold', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='critical', max_length=20)),
                ('risk_score_threshold', models.FloatField(blank=True, null=True)),
                ('cve_required', models.BooleanField(default=False)),
                ('zero_day_only', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=True)),
                ('create_jira_ticket', models.BooleanField(default=False)),
                ('create_servicenow_ticket', models.BooleanField(default=False)),
                ('email_recipients', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('jira_integration', models.ForeignKey(blank=True, limit_choices_to={'integration_type': 'jira'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_alert_rules', to='integrations.integration')),
                ('notify_users', models.ManyToManyField(blank=True, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
                ('servicenow_integration', models.ForeignKey(blank=True, limit_choices_to={'integration_type': 'servicenow'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicenow_alert_rules', to='integrations.integration')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical_vulnerability', 'Critical Vulnerability'), ('high_vulnerability', 'High Vulnerability'), ('zero_day', 'Zero-Day Vulnerability'), ('anomaly', 'Anomaly Detected'), ('scan_completed', 'Scan Completed'), ('risk_threshold', 'Risk Threshold Exceeded')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('jira', 'JIRA'), ('servicenow', 'ServiceNow'), ('slack', 'Slack'), ('webhook', 'Webhook')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('alert_data', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('external_ticket_id', models.CharField(blank=True, max_length=255)),
                ('external_ticket_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='integrations.integration')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scanning.scan')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scanning.scantarget')),
                ('vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scanning.vulnerability')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', '-created_at'], name='alerts_aler_alert_t_b7affd_idx'), models.Index(fields=['status', '-created_at'], name='alerts_aler_status_e70a14_idx'), models.Index(fields=['channel', '-created_at'], name='alerts_aler_channel_09cfdb_idx'), models.Index(fields=['severity', '-created_at'], name='alerts_aler_severit_f1bbe4_idx')],
            },
        ),
    ]
