# Generated by Django 4.2.3 on 2025-12-26 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('cvss_v2_score', models.FloatField(blank=True, null=True)),
                ('cvss_v2_vector', models.CharField(blank=True, max_length=200)),
                ('cvss_v3_score', models.FloatField(blank=True, null=True)),
                ('cvss_v3_vector', models.CharField(blank=True, max_length=200)),
                ('cvss_v31_score', models.FloatField(blank=True, null=True)),
                ('cvss_v31_vector', models.CharField(blank=True, max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], max_length=20)),
                ('affected_products', models.JSONField(default=list)),
                ('cpe_list', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('vendor_advisory', models.URLField(blank=True, null=True)),
                ('cwe_id', models.CharField(blank=True, max_length=20)),
                ('exploit_available', models.BooleanField(default=False)),
                ('patch_available', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date', '-cvss_v3_score'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scan_type', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_config', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scan_results', models.JSONField(default=dict)),
                ('scan_summary', models.JSONField(default=dict)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('scan_duration', models.FloatField(blank=True, null=True)),
                ('scanner_version', models.CharField(blank=True, max_length=50)),
                ('scan_engine', models.CharField(blank=True, max_length=100)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('cve_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('evidence', models.JSONField(default=dict)),
                ('recommendation', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('vulnerability_type', models.CharField(blank=True, max_length=100)),
                ('affected_component', models.CharField(blank=True, max_length=500)),
                ('remediation_steps', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('detection_count', models.IntegerField(default=1)),
                ('cve_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='scanning.cvedata')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanning.scan')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-severity', '-cvss_score'],
            },
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('target_type', models.CharField(choices=[('web', 'Web Application'), ('network', 'Network'), ('api', 'API'), ('code', 'Source Code'), ('container', 'Container')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanning.scantarget'),
        ),
        migrations.CreateModel(
            name='CVEHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('score_changed', 'Score Changed'), ('severity_changed', 'Severity Changed')], max_length=50)),
                ('old_data', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='scanning.cvedata')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cvedata',
            index=models.Index(fields=['cve_id'], name='scanning_cv_cve_id_e40e30_idx'),
        ),
        migrations.AddIndex(
            model_name='cvedata',
            index=models.Index(fields=['severity', '-cvss_v3_score'], name='scanning_cv_severit_439b41_idx'),
        ),
        migrations.AddIndex(
            model_name='cvedata',
            index=models.Index(fields=['published_date'], name='scanning_cv_publish_4dbfc0_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['scan', '-detected_at'], name='scanning_vu_scan_id_902174_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['severity', '-cvss_score'], name='scanning_vu_severit_f0540b_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['cve_id'], name='scanning_vu_cve_id_2b5c24_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['is_false_positive', '-detected_at'], name='scanning_vu_is_fals_e18e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['target', '-started_at'], name='scanning_sc_target__458d08_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status', '-started_at'], name='scanning_sc_status_fe9e86_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['initiated_by', '-started_at'], name='scanning_sc_initiat_fea570_idx'),
        ),
    ]
