# Generated by Django 4.2.3 on 2026-05-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['scan_type', '-started_at'], name='scanning_sc_scan_ty_d9a959_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['completed_at'], name='scanning_sc_complet_c9f95b_idx'),
        ),
    ]
